# Generated by Django 3.1.3 on 2020-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('device_type', models.CharField(choices=[('SR', 'Siren'), ('SP', 'Speaker')], default=('SR', 'Siren'), max_length=2, verbose_name='Тип устройства')),
                ('location_address', models.CharField(blank=True, max_length=120, verbose_name='Адрес размещения')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('zone_radius', models.IntegerField(verbose_name='Радиус зоны звукопокрытия')),
            ],
            options={
                'verbose_name_plural': 'Устройства оповещения',
            },
        ),
    ]
