# Generated by Django 3.1.3 on 2021-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningdevice',
            name='device_type',
            field=models.CharField(choices=[('SR', 'Сирена'), ('SP', 'Громкоговоритель')], default=('SR', 'Сирена'), max_length=2, verbose_name='Тип устройства'),
        ),
    ]
